### ISSUE TITLE
Göteborg är inte intressant :-)

### ISSUE THREAD

**Issue by Ampelmann55** [mdiwing/GitWorkshopPractice#9]
sjd

Göteborg är inte intressant :-)

_Originally posted by @mdiwing in https://github.com/mdiwing/GitWorkshopPractice/pull/7#pullrequestreview-914159255_

**Comment by mdiwing** [comment]
Ok låt gå för den här gången :-)

**Comment by mdiwing** [comment]
Du får ha med ditt bidrag också
